import openai
import re

class OpenAIReviewerAgent:
    def __init__(self, api_key):
        openai.api_key = api_key

    def review_analysis(self, analysis):
        prompt = f"""Du bist ein Business-Reviewer. Bewerte die folgende Geschäftsmodell-Analyse auf Qualität, Klarheit und Vollständigkeit. Gib konstruktives Feedback und eine Punktzahl von 1 bis 10.
                Analyse: {analysis} """

        response = openai.chat.completions.create(
            model="gpt-4",
            messages=[{"role": "user", "content": prompt}]
        )
        return response.choices[0].message.content.strip()

    def extract_score(self, feedback_text):     #generated by chatgpt to extract points from a prompt
        match = re.search(r"(\b[1-9]|10)\b\s*/?\s*10", feedback_text)
        return int(match.group(1)) if match else 0